### ISSUE TITLE
Graficar datos que se están muestreando

### ISSUE THREAD

**Issue by pheppk** [firstmakers/senso#2]
El Gráfico debiera mostrar los datos que el usuario definió, no los que el software toma por defecto (con el botón derecho). Si el usuario define el Intervalo y las Muestras, al hacer "play" debiera comenzar a graficar esa toma de datos.

Si el usuario quiere usar uno de los Intervalos por defecto (botón derecho) el software debiera actuar igual que al usar la consola. Sugiero dejar la funcionalidad del botón derecho como un menú arriba ("Muestras" o un nombre más apropiado), agregando la toma de datos cada 1, 10, 30 y 60 minutos.

Sugiero revisar tener un solo sistema de toma de datos: solo desde el Menú "Muestras" en que hay valores por defecto (para hacerla simple) y además, uno que sea "Definir Intervalo...." que abre una ventanilla para definir el Intervalo y el número de Muestras. La consola quedaría reducida a los botones de play, detenerse y stop.

**Comment by EdisonDelgado** [comment]
@pheppk  con respecto al menú, en mac el menú se separa de la interfaz, no complica que quede dentro como se ve a continuación?

![captura de pantalla 2016-01-05 a las 3 55 14 p m](https://cloud.githubusercontent.com/assets/1309328/12124561/da9cb276-b3c4-11e5-8c40-73514807b65d.png)

Para programar es mas fácil ya que se hace una sola vez y se vería igual en todas las plataformas, de lo contrario, tendría que duplicar menús y esconder elementos para mac lo que se hace más difícil de mantener si la aplicación sigue creciendo.

En los sensores agregué otra distribución para poner un menú que se abre para configurar el nombre del sensor y el checkbox para mostrar o no el sensor en el gráfico.

**Comment by pheppk** [comment]
Creo que queda bien como lo ilustras. Lo único que cambiaría es que la consola solo quedaría con play, pause y stop --- y sin la posibilidad de definir ahí la muestra.
