### ISSUE TITLE
Guardar datos de un muestra

### ISSUE THREAD

**Issue by pheppk** [firstmakers/senso#3]
Actualmente, el guardar los datos de un muestreo es opcional, pero de todas las muestras se van guardando en memoria por si el usuario decide guardarlas, lo que puede ocasiona una caída del sistema por sobrepasar el límite de almacenamiento en memoria.

Veamos opciones:

1) Preguntar al inicio de cada nuevo muestreo si va a querer guardar los datos. Si indica que no, fácil. Si indica que si, se pide nombre/ruta archivo y se van guardando en formato excel. 

2) al final de un muestreo, el usuario decide si guarda o no los datos en memoria desde el menú Archivo, con la opción "Guardar..."

Ver si es posible ir guardando periódicamente y salvando el archivo por si se cae el SO. Eventualmente se podría activar una "excepción" con el SO que permita guardar los datos en la medida que se llene la memoria. Otra opción es incluirle una BD SqlLite ---.

**Comment by EdisonDelgado** [comment]
@pheppk la opción 1 es mas fácil de implementar de hecho así está actualmente pero con la diferencia que la ruta de los datos se pregunta al clickear el botón guardar. El único problema de este método es que si en algún momento se desconecta un sensor  la medición queda corrupta porque desde el inicio se crearon las columnas de excel y los índices no van a corresponder (lo mismo si se agrega uno). La ventaja de esto es que no ocupa memoria RAM.

La segunda opción ocupa RAM porque sí o sí hay que almacenar lo datos en la memoria y esta crecerá  a medida que va tomando datos.

una duda, ¿ cual sería el caso en que tome una cierta cantidad de muestras y no las guarde? si quiero ver el valor de los sensores basta sólo con ver las cajas de los sensores esos muestran el valor actual. El gráfico también se puede iniciar con el botón derecho.

**Comment by pheppk** [comment]
Respuesta a la duda: en muchas ocasiones el usuario solo quiere observar el gráfico que se está generando, y no pretende hacer un análisis posterior con Excel --- esto es frecuente cuando uno está probando sensores, preparando un experimento o un proyecto --- prototipando.
Por cierto, en un proyecto "serio", el usuario no querrá perder ningún dato.

Respecto de las opciones: es una buena duda definir qué es mejor. Me inclino por la opción 1 (que después podremos volver a revisar) en que el usuario explícitamente avise al inicio si va a querer guardar los datos o no. Si se desconecta un sensor --- mala pata. Si se cae el SO por exceso de datos: es un problema que debiéramos abordar: o bien cerrar y abrir periódicamente el archivo Excel (así solo se pierde las últimas muestras y no todo) y en cada cierra se libera memoria o bien generar una excepción con el SO.

**Comment by EdisonDelgado** [comment]
@pheppk Creo personalmente que lo mejor es  tener una copia de la última medición, ahora los datos se guardan desde el menú archivo, entonces si yo hice una medición de prueba luego otra medición y la quiero guardar el software al iniciar la última medición borrará la anterior y me guardará la actual (sin preguntar) entonces cuando le de al botón guardar me guardará la última medición.Con esto Evitamos conflictos cuando el usuario programa una medición y cuando la inicia desde el botón Iniciar y evitamos crear cuadros de diálogos al inicio de cada medición ( acá serían dos uno para preguntar si quiere o no guardar y el otro para obtener la ruta del archivo).

En resumen, el software siempre contará con la última medición disponible para ser guardada y esta se puede guardar desde el menú "Archivo->Guardar..." 

Estoy atento a sus comentarios.

**Comment by pheppk** [comment]
De acuerdo Edison, probemos esa opción.
Avísame cuando tengas una nueva versión.
Saludos
