### ISSUE TITLE
Indicar mejor posibilidad de cambiar rótulo de sensor

### ISSUE THREAD

**Issue by pheppk** [firstmakers/senso#4]
Al tener varios sensores tomando muestras, se puede cambiar el color del gráfico respectivo y también el nombre del sensor (actualmente, es por ejemplo, "Temperatura" o "Luminosidad") en la etiqueta de color del sensor respectivo en la parte izquierda de la interfaz. Poder cambiar el nombre no es obvio (no es obvio clicar sobre la palabra Temperatura o Luminosidad.

Sugiero hacerlo más obvio, tal vez con un rótulo "nombre:" antes del Nombre por defecto y dejar este en un casillero que sugiera que es editable.

**Comment by EdisonDelgado** [comment]
@pheppk propongo abstraer todas las opciones del sensor en un menú, por el espacio reducido no se puede poner más etiquetas y se ve sobrecargado. La idea sería dejar en el bloque del sensor un botón de configuración donde se despliegan las opciones que tenemos actualmente, por ejemplo; 

---

opciones

---

[  ] Mostrar en el gráfico
[  ] Color del sensor

Nombre
[_____________]

---

Esto nos deja una interfaz mucho más limpia.

Estoy atento a sus comentarios.

**Comment by pheppk** [comment]
Edison: me parece bien esta propuesta veamos como queda en un Menú.
Avísame cuando esté para probarla
