### ISSUE TITLE
Definir inicio de muestreo en hora predefinida 

### ISSUE THREAD

**Issue by pheppk** [firstmakers/senso#5]
Actualmente el muestreo comienza cuando el usuario lo activa con el botón derecho o bien apretando el play en la consola.
Sería útil poder indicar que el muestreo comience a una cierta hora (hora:minuto:segundo) predefinida por el usuario. Por ejemplo, que la medición parta a las 12:00:00 --- y no tener que esperar justo esa hora.

**Comment by EdisonDelgado** [comment]
@pheppk  duda, acá sólo se podrá configurar una medición dentro de las próximas 24 horas o también se considera poder programar la medición dentro de 3 días una semana. ¿cual es el rango mínimo y máximo para programar  una medición?

**Comment by pheppk** [comment]
Hola, dejémoslo en esta versión para las próximas 24 horas, es decir, solo reloj, no fecha.
Los rangos son horas y minutos.
Creo que la idea es darle una hora de inicio, que se considera como la siguiente. Por ejemplo: si se indica a las 14:30, entonces es a las siguientes 14:30 (hoy o mañana si ya pasó hoy).
En cuanto al rango, creo que intervalos entre 1 segundo y 60 minutos estaría bien y tomando hasta 999 muestras. Se aceptan sugerencias!
